### PR TITLE
Add option to keep generated files in current dev directory

### PR DESCRIPTION
**Pull request by kpitn**
We need an option to keep generated file in current dev directory.

This PR can resolve the issue #323

### CODE REVIEW

**Comment by Igloczek** [comment]
Sorry but I'm not going to accept this pull request.

As I said in the mentioned issue, you seem to be using Magento in a wrong way, against best practices.
By default in developer mode these files are not removed, you are removing them manually by running the `bin/magento setup:static-content:deploy`.

**Comment by kpitn** [comment]
You don't understand, the goal of this PR.

When your server don't have Gulp or whatever css processor.
You need to create styles.css in your theme design, to push it to your repository.
Without this PR, I need to manualy copy styles.css from static directory into my theme directory.

I don't think i'm the only one with this problem.

It's ok if you refuse this PR, i will keep this for my project.

**Comment by Igloczek** [comment]
Well, you should think about better deployment pipeline or as you said, just fork it and adjust to your needs, if that's not an option.

**Comment by Igloczek** [comment]
BTW. Would be easier to understand the goal, if the PR will have a detailed description 😉

**Comment by kpitn** [comment]
I mention this isssues : https://github.com/SnowdogApps/magento2-frontools/issues/323

Because I was doing like the reporter says : 
`
{
  "blank": {
    "src": "vendor/snowdog/theme-blank-sass",
    "dest": "app/design/frontend/Snowdog/blank",
    "locale": ["web"],
    "ignore": [".test"]
  }
}
`
But it's no longer working.

**Comment by kpitn** [comment]
It's not really a workaround, because if i want to have styles.css in my dev theme directory.
I need to add two themes, one compiling in pub, one compiling in dev.
With my PR, you don't need to compile twice.

**Pull request closed without merging**
