### PR TITLE
Moved SourceMap to separate file.

### PR DESCRIPTION
**Pull request by kirmorozov**
Generating source map with content next to original file.
Helps to read minified css.
It enables sourceMap at all times except when disabled.

### CODE REVIEW

**Comment by kirmorozov** [comment]
Solution for: https://github.com/SnowdogApps/magento2-frontools/issues/275

**Comment by Igloczek** [comment]
@kirmorozov what kind of issue do you mean? The auto-generated PRs with dependencies updates?

**Comment by kirmorozov** [comment]
@Igloczek
What stops you from merging PR?

> greenkeeper/verify — Waiting for status to be reported
I have no way to influence gatekeeper.

**Comment by Igloczek** [comment]
Lack of time.

**Pull request merged**
