### PR TITLE
Added compass support

### PR DESCRIPTION
**Pull request by herveguetin**

### CODE REVIEW

**Comment by Igloczek** [comment]
Sorry but I'm not going to merge this. Compass is outdated (1.5 year without any release), slow and require extra configuration (ruby + compass installed in system).
In most cases users can eaily have same functionality using Bourbon, b/c are using only simple minixins, not things like generating sprites.

**Comment by Igloczek** [comment]
Even authors say it on githib reposiotry
> Depreciated: Compass is no longer supported

**Comment by herveguetin** [comment]
Ok, no problem, this is your call :)

I just added Compass support because design folks in my company use it so I thought it could be useful for others.

BTW, if you looked at the code, the switch from "regular" Sass to Compass is automatic as soon as you add the "compass" property in the theme JSON config. So, not using Compass is just a matter of not populating the "compass" property.

**Comment by Igloczek** [comment]
I don't want to promote deprecated solutions and carying about them during next updates.
Let's have a look on Bourbon, it should replace Compass in your workflow without any issues :) (we use it on Magento 1.9.x RWD theme - swich take about 15min, b/c some mixins are not necessary or have a bit diffrent name)

**Comment by herveguetin** [comment]
I totally agree with you and must confess that I did not now that Compass was no longer supported. Will talk with my guys and "boooo" them while asking them to try switching to Bourbon.

Let me also use this comment to thank you a ton for your sass M2 module.

**Comment by Igloczek** [comment]
You're welcome 😉

**Pull request closed without merging**
