### PR TITLE
Allow imports from root node_modules for scss

### PR DESCRIPTION
**Pull request by GrimLink**

### CODE REVIEW

**Comment by Igloczek** [comment]
It needs to be optional and configurable, otherwise, it can slow down compiling for everyone.

**Comment by GrimLink** [comment]
@Igloczek I have changed it to a config via the themes.json

**Comment by tdgroot** [comment]
+1 on this change.

**Comment by GrimLink** [comment]
@Igloczek I have updated my PR with the latest release.
Any chance you could take a look and maybe add it?

**Comment by matthew-muscat** [comment]
+1 on this change here — i've needed this capability from frontools in one of our projects

**Comment by GrimLink** [comment]
Hoi @Igloczek 
I noticed another minor release -> [releases/tag/1.8.1](https://github.com/SnowdogApps/magento2-frontools/releases/tag/1.8.1)
Any chance this PR can also be reviewed?

**Comment by Igloczek** [comment]
Sure, 1.9.0 will probably get those chages if everthing will be fine.

**Review by Igloczek — APPROVED** [review]

**Pull request merged**
