### PR TITLE
Cleaned up unused variables and added comments

### PR DESCRIPTION
**Pull request by timneutkens**
Also removed gulp-csslint since it's not used at the moment. We might integrate http://stylelint.io/.

### CODE REVIEW

**Comment by Igloczek** [comment]
I'm using Stroustrup indentation style, so please revert changes related to indention of `if` statements.

**Comment by timneutkens** [comment]
Will do, did not know that until you mentioned it in the other pull request :)

**Comment by Igloczek** [comment]
About styles linting - I'm going to port tests from "magento2-theme-blank-sass" - #23

**Comment by timneutkens** [comment]
Changed the if statements.

**Pull request merged**
