### PR TITLE
Inheritance is broken when child name is : parentname+'suffix'

### PR DESCRIPTION
**Pull request by vberthet**
If parent theme config is: 
```
"src": "app/design/frontend/Sample/Sample",
"dest": "pub/static/frontend/Sample/Sample",
```
And child theme:
```
"src": "app/design/frontend/Sample/Samplechild",
"dest": "pub/static/frontend/Sample/Samplechild",
```
generated path will be : `child/var/www/sample/pub/static/frontend/Sample/Samplechild`

### CODE REVIEW

**Comment by Igloczek** [comment]
Where did you installed Frontools? Did you did this via composer and path is `vendor/snowdog/frontools`?

**Comment by vberthet** [comment]
Frontools is installed via composer in vendor/snowdog/frontools with a symlink in tools/

**Comment by Igloczek** [comment]
Okay, so "generated path will be" mean what you want to get that path or you get right now after changes? Could you show me before / after comparison, with some description why you think it's necessary?

I'm not facing any issues and we have few project based on top of this code and everything works fine, so it's highly possible that's not a code problem, but just your configuration.

**Comment by Igloczek** [comment]
Closing due to an unclear description and lack of answers.

**Pull request closed without merging**
